### ISSUE TITLE
About the test images

### ISSUE THREAD

**Issue by InFistLee** [maximeraafat/BlenderNeRF#13]
Thanks for the tool which really helps a lot!

I wonder is there anyway to generate test rendering images together with the camera pose? I found that only testing camera information is generated, which makes me unable to calculate the metrics like PSNR when rendering on test camera pose. Is there a way that I can get these testing images just like the training images?

Thanks!

**Comment by InFistLee** [comment]
Also, I found that when using COS method, the sampled testing camera pose is actually not on the sphere and pointing to the center of the scene. I guess that the testing poses are randomly sampled unlike training poses, which might be a problem in 360 scene.

**Comment by maximeraafat** [comment]
Hi @InFistLee, thanks for your interest and questions!

Creating the test renders basically boils down to just rendering the scene from the test camera. You can simply do that by selecting the test camera to be the active one, and then rendering the scene under **Render > Render Animation** (in the Topbar). Note that by default the rendered images will be stored into the `/tmp/` directory, you might want to change that. Pasting the renders into a `test` folder within the created **BlenderNeRF** dataset folder should do the trick.

As for the the test poses for the **COS** method, these will be the camera pose for the selected **Camera** (highlighted in blue in the screenshot). If you want to have a test camera with poses sampled from the same sphere, you can directly select the **BlenderNeRF Camera** as active camera in the **COS** method (visible once you pressed the **Camera** button under **Preview**). In order to get different poses for training and testing cameras with the **COS** method, I would suggest first only rendering training frames with a specific seed, and then only test frames with a different seed.

<img width="202" alt="COS" src="https://user-images.githubusercontent.com/51931580/221573600-bde6a37f-3c60-4289-8d55-5440772e4a76.png">

Let me know if anything is still unclear or if you have further questions!
