### ISSUE TITLE
Is the release version folder name wrong?

### ISSUE THREAD

**Issue by Mcskiller** [maximeraafat/BlenderNeRF#4]
Hi, I found that the release version's name will cause `ModuleNotFoundError: No module named 'BlenderNeRF-2'`, to fix this I have to manually change the folder name to `BlenderNeRF`. 

Is there any way to fix this problem before release? It's hard for a blender noob like me to figure out what happened.

**Comment by maximeraafat** [comment]
Hi, thanks for notifying me about this issue!

I've lately been quite short in time but I'll have a look into this soon and will bring a fix to it. I'll be careful to not reproduce this error in the next releases and will try to fix this for the current ones.

**Comment by maximeraafat** [comment]
Hi, the issue should have been fixed now.

It appears that python perceives the last part of the GitHub version tag extension (the `.0.0` in `BlenderNeRF-2.0.0`) as a file format extension, and therefore ignores that part when loading the module. I provided a quick fix by renaming the tags as _v1_ and _v2_ instead of _v1.0.0_ and _v2.0.0_. Future versions will follow this terminology to avoid any problems.

Releases are a safe way to keep track of changes and versions, but I recommend installing **BlenderNeRF** as a zip file from the green button above the list of files. This way you should never encounter module loading errors. But when installing from the release versions, be sure to download the zip file and not the tar file, as Blender won't recognise the latter.

Please let me know if you run into other problems with the add-on.

**Comment by Mcskiller** [comment]
Hi, sorry about the late reply, thanks for helping with this. 

Have a nice day!👏
