### ISSUE TITLE
how do I begin?

### ISSUE THREAD

**Issue by adispare** [maximeraafat/BlenderNeRF#7]
Hi, maybe I'm missing something. Can I feed images for them to be trained or should I come with an already trained set? In both cases I was not very clear how to begin with this. 

Thanks!

**Comment by maximeraafat** [comment]
Hi @adispare, let me perhaps clarify the aim of this add-on. **BlenderNeRF** is a tool to create datasets which can directly be used to train a NeRF. It does not allow you to visualise NeRFs within Blender, but instead to obtain all the data necessary to train them, notably the camera poses from a scene in Blender.

Practically, this means that given a scene in Blender with a manually defined camera trajectory, you can simply extract the camera poses and render the corresponding views within a click using this add-on.  If you just wish to create a NeRF regardless of any predefined camera trajectory, you can also obtain random camera poses on a sphere while the camera points at the centre of the sphere.

I hope this answers your question, and let me know if you have any further doubts :)

**Comment by avclubvids** [comment]
I'll add in here, can you explain the TTC method - both what it is and how to use it? The SOF and COS methods both make total sense.

**Comment by maximeraafat** [comment]
Hi @avclubvids, sure, let me give some more details on the TTC method. This method is basically a simple way of having separate camera `transforms.json` files for a training trajectory that you would like to use for training a NeRF, and another testing trajectory for which you would like to evaluate the trained NeRF on

 Let me know whether it's still unclear :)

**Comment by avclubvids** [comment]
So, just to make sure I have this right:

training = same type of JSON as the SOF method, just without the settings to subsample the camera animation?
testing = camera animated in Blender to be exported to JSON for rendering in iNGP/NeRFStudio?

if yes, I **_love_** the testing camera option, but I'd like the option of having the SOF settings on the training camera. Does that make sense?

**Comment by maximeraafat** [comment]
Hi @avclubvids, please excuse me for the late reply.

Yes you got it right for both. There are actually two fairly simple ways to get a subset of frames for the training camera JSON file, alongside a testing camera JSON file.

1. You can deactivate the **Test** option available in the **BlenderNeRF shared UI** panel, and run the **SOF** method. Then you can deactivate the **Train** option and reactivate the **Test** option, and run the **TTC** method for a selected test camera
2. Or you can simply do the same trick of switching the **Train** and **Test** buttons with **TTC**, and change the frame step under the default Blender **Properties** window, under **Output Properties** > **Frame Range**.

Once you got both your data for training and testing in separate folders, you can simply combine them.

It might actually be useful to know that **BlenderNeRF** uses all the rendering properties defined in Blender directly (frame start, frame end, resolution, etc.).

**Comment by avclubvids** [comment]
Ok perfect, that's what I hoped for. I'll probably use SOF/COS for the training cameras and use TTC for making cameras to render in iNGP/NERFStudio

**Comment by TheLordSaiyan** [comment]
I'm also trying to import a simple camera move from Blender to Instant-NGP. Did you figure it out ? Even tough the path tot the file is correct, i wont create the animation I did in blender.

**Comment by avclubvids** [comment]
AFAIK it is not currently possible in iNGP. It is possible in NeRF Studio but I think this is an NVIDIA limitation.

**Comment by maximeraafat** [comment]
Hi @TheLordSaiyan,

Are you referring to test camera paths? In accordance with @avclubvids, I could not find any way of importing test cameras directly in the NGP graphical user interface. However, you can obtain test renders by running a python script included with NGP.

Here's what you need to do (I assume here that you are using a Linux-based shell)

```bash
python instant-ngp/scripts/run.py --training_data=<trainPath>\
                                  --screenshot_transforms=$<testJson> \
                                  --screenshot_w=<width>--screenshot_h=<height>\
                                  --screenshot_dir=<testPath> \
                                  --save_snapshot=snapshot.msgpack \
                                  --n_steps=<iterations>
```

* `<trainPath>` : path to your training data containing the training images and the `transforms_train.json` file
*  `<testJson>` : path to your `transforms_test.json` file
*  `<width>` and  `<height>` : output dimensions of your rendered images
* `<testPath>` : path in which you want to save your test images
* `<iterations>` : number of training steps

You can see an example of this code in action in this [COLAB notebook](https://colab.research.google.com/drive/1dQInHx0Eg5LZUpnhEfoHDP77bCMwAPab?usp=sharing#scrollTo=Z8f0ywQSYMNH), where you can also run NGP if you do not have any NVIDIA GPU.

I hope this answered your question, let me know if you have any further issues!

**Comment by yuehaowang** [comment]
> Hi @avclubvids, please excuse me for the late reply.
> 
> Yes you got it right for both. There are actually two fairly simple ways to get a subset of frames for the training camera JSON file, alongside a testing camera JSON file.
> 
> 1. You can deactivate the **Test** option available in the **BlenderNeRF shared UI** panel, and run the **SOF** method. Then you can deactivate the **Train** option and reactivate the **Test** option, and run the **TTC** method for a selected test camera
> 2. Or you can simply do the same trick of switching the **Train** and **Test** buttons with **TTC**, and change the frame step under the default Blender **Properties** window, under **Output Properties** > **Frame Range**.
> 
> Once you got both your data for training and testing in separate folders, you can simply combine them.
> 
> It might actually be useful to know that **BlenderNeRF** uses all the rendering properties defined in Blender directly (frame start, frame end, resolution, etc.).

Hi @maximeraafat, thanks for your great work!
I'm still confused about the steps to generate train and testing splits. I would like to render testing data instead of camera information only since I need ground truth images for numerical evaluation.

The file format I'm using is "NeRF". I tried the given steps above but the "transforms_test.json" file will contain some missing paths, like "test/0001.png". I guess I misunderstood those instructions.
Could you please provide a step-by-step tutorial with figures or videos on creating a standard NeRF synthetic dataset? Thank you.

**Comment by maximeraafat** [comment]
Hi @yuehaowang,

The add-on does not support rendering test imagers per design. You can however render test images by simply selecting the desired test camera and pressing the `Render Animation` command in Blender.

As for the missing paths, let me clarify how to use each of the methods in order to create a train and test NeRF dataset. Youl will need to have both `Train` and `Test` buttons  selected in the shared user interface. 

* `SOF` : select the desired camera and play the operator. Your training dataset will consist of every **n**-th render from this camera, alongside the `transforms_train.json` file containing every **n**-th camera pose of your selected animated camera (**n** is the chosen frame step). The `transforms_test.json` file will contain every camera pose in the selected animated camera

* `TTC` : when playing the operator, your training data will be constructed from **n** frames rendered using the `Train Cam`, while the `transforms_test.json` file will contain every camera pose from the selected `Test Cam`. Here, **n** is the number of training frames (controllable with the `Frames` property) that you can set in the TTC UI panel, such that you can essentially have a different number of train and test frames.

* `COS` : the training data will be constructed from **n** frames rendered using the `BlenderNeRF Camera` (visible with the respective preview button), while the `transforms_test.json` file will contain every camera pose from the selected `Camera`. Here, **n** is the number of training frames (controllable with the `Frames` property) that you can set in the COS UI panel.

I hope this helps and is a bit more informative! If you still have uncertainties, feel free to open more questions. I am also working on a tutorial video that will demonstrate each of the methods and explain how to use them, so stay tuned! :)
